### ISSUE TITLE
Set up consistent screen width breakpoints

### ISSUE THREAD

**Issue by xujustinj** [loolabs/waterpark#136]
Currently, some of our components avoid using the common media queries in `styles/device.ts`, in favour of their own styles. We should refactor the whole app to use one consistent set of width media queries that we can plug everywhere.

At the moment I think we have too many breakpoints to work with, so we should sync with design on which points should be breakpoints.

**Comment by evtyz** [comment]
Resolved with https://github.com/loolabs/waterpark/pull/174.
