### ISSUE TITLE
Searching and Filtering

### ISSUE THREAD

**Issue by amanmathur99** [loolabs/waterpark#64]
As a student, I want to be able to search and discover particular things I am interested in and browse clubs/events based on filters.

Reach out to the design team before starting on this because specifics are not finalized yet. 

![image.png](https://images.zenhubusercontent.com/5ffa17071ab1da4382b228cc/43d5ad0d-759c-41d0-9bdd-f77a897b4192)

**Comment by jeffzh4ng** [comment]
Replacing with https://github.com/loolabs/waterpark/issues/164
