### ISSUE TITLE
Setup Email User (use-case)

### ISSUE THREAD

**Issue by ShreyasPrasad** [loolabs/waterpark#69]
This ticket involves both researching potential email sending use-case implementations and implementing one. This use-case/module would then be invoked by different domains across the app for all external user correspondence.

This ticket will be updated with the evaluation of potential approaches:

1. SMTP + nodemailer implementation. Similar to how auth is implemented, this would depend on creating an email service handler (like UserAuthHandler) which is invoked by the email use-case. This ensures that we can rip out nodemailer in the future if we switch out to any new framework.

2. Using mailchimp or mandrill to construct and send email templates instead.

**Comment by jeffzh4ng** [comment]
Decision on user service design has been done.
